#!/bin/bash
if [ `uname` = 'Darwin' ] ; then
  battery_status=`pmset -g batt`
  percent=`echo $battery_status | egrep "([0-9]+\%).*" -o --colour=auto | cut -f1 -d";"`
  power_source=`echo $battery_status | egrep "'(.*) Power'" -o`
fi

case $power_source in 
  "'Battery Power'"*)
    battery_icon=🔋
    ;;
  "'AC Power'"*)
    battery_icon=⚡️
    ;;
  *)
    battery_icon=🔥
esac

if (( ${percent%?} > 70 )); then 
    bg_colour='colour2'
elif (( ${percent%?} > 20 )); then 
    bg_colour='colour3'
else 
    bg_colour='colour1'
    battery_icon=💀
fi
echo "#[fg=$bg_colour]#[bg=$bg_colour,fg=colour16]$battery_icon $percent #[fg=colour5,bg=$bg_colour]"
