#!/bin/bash
source ~/.aliases
music_icon=
play_icon=
pause_icon=

plex_output=`curl -H 'Accept: application/json' http://localhost:32400/status/sessions?X-Plex-Token=$PLEX_TOKEN | jq '.MediaContainer.Metadata[0]'`

artist=`jq -r '.grandparentTitle' <<< "$plex_output"`
title=`jq -r '.title' <<< "$plex_output"`

echo "#[bg=default,fg=green] $artist - $title $music_icon"
